/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function YcubeLogo(props) {
  const { nodes, materials } = useGLTF('/assets/careersLogo.gltf')
  return (
    <group {...props} dispose={null} scale={[30,30,30]} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
      />
    </group>
  )
}

useGLTF.preload('/assets/careersLogo.gltf')



// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function YcubeLogo(props) {
//   const { nodes, materials } = useGLTF('/assets/Ycube.gltf')
//   return (
//     <group {...props} dispose={null} scale={[30,30,30]} >
          
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.mesh_0.geometry}
//         material={nodes.mesh_0.material}
//       />
//     </group>
//   )
// }
// useGLTF.preload('/assets/Ycube.gltf')